#server config file
server:
  port: 18092
  servlets:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

#DataSource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vb0e5pwz6sgq1x3h2o.mysql.zhangbei.rds.aliyuncs.com:3306/monty?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: montylee
    password: Limeng_1234


#mybatis plus config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0

# kaptcha config
kaptcha:
  height: 50
  width: 200
  content:
    length: 5
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1



